zuul:
  routes:
    user_service:
      path: /user_service_api/**
      serviceId: USER_SERVICE
    comment_service:
      path: /comment_service_api/**
      serviceId: COMMENT_SERVICE
    adopt_service:
      path: /adopt_service_api/**
      serviceId: ADOPT_SERVICE
    notification_service:
      path: /notification_service_api/**
      serviceId: NOTIFICATION_SERVICE
    pet_category_service:
      path: /pet_category_service_api/**
      serviceId: PET_CATEGORY_SERVICE
  sensitive-headers: Cookie, Set-Cookie

server:
  port: 8088

spring:
  application:
    name: api_gateway
  servlet:
    multipart:
      max-file-size: 500MB

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Increase the Hystrix timeout (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ...