zuul:
  routes:
    user_service:
      path: /user_service_api/**
      url: http://localhost:8080
    comment_service:
      path: /comment_service_api/**
      url: http://localhost:8081
    adopt_service:
      path: /adopt_service_api/**
      url: http://localhost:8082
    notification_service:
      path: /notification_service_api/**
      url: http://localhost:8083
    pet_category_service:
      path: /pet_category_service_api/**
      url: http://localhost:8084
  sensitive-headers:

server:
  port: 8088

spring:
  application:
    name: api_gateway
  servlet:
    multipart:
      max-file-size: 500MB